### ISSUE TITLE
whitelist example please

### ISSUE THREAD

**Issue by jfix** [vbauer/manet#18]
Hello, I'm trying to configure manet to only allow connections from two IP addresses. I guess the whitelist option is there for that.

I've tried to replace the ```whitelist``` option's default value with this:

```
"whitelist": [
        "127.0.0.1",
        "192.168.0.1"
    ]
```

When attempting to launch manet The following error is shown on the command line:

```
$ manet --port 3000

/usr/local/lib/node_modules/manet/node_modules/nconf/lib/nconf/stores/file.js:141
      throw new Error("Error parsing your configuration file: [" + self.file +
            ^
Error: Error parsing your configuration file: [/usr/local/lib/node_modules/manet/src/config/default.json]: Unexpected token /
    at File.loadSync (/usr/local/lib/node_modules/manet/node_modules/nconf/lib/nconf/stores/file.js:141:13)
    at Provider.add (/usr/local/lib/node_modules/manet/node_modules/nconf/lib/nconf/provider.js:137:23)
    at Provider.file (/usr/local/lib/node_modules/manet/node_modules/nconf/lib/nconf/provider.js:63:15)
    at load (/usr/local/lib/node_modules/manet/src/config.js:76:10)
    at Object.read (/usr/local/lib/node_modules/manet/src/config.js:87:30)
    at Object.main (/usr/local/lib/node_modules/manet/src/manet.js:133:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/manet/bin/manet:5:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

While I think the ```whitelist``` type is array, this is maybe not the right way to supply IP addresses. Or it could be a bug, but I haven't been able to find the appropriate place in the source code; apparently ```nconf``` is being used to validate the configuration file.

Thank you for your help in advance,
Jakob.

**Comment by vbauer** [comment]
Actually white list contains RegExp to describe URL addresses for screenshot capturing.

For example you want to allow to make screenshots only for google.com and all sub-domains. White list allows to do it.

Actually I feel doubts about this parameter. Maybe I need to remove it or change behaviour to something more useful.

**Comment by jfix** [comment]
Maybe there's another way of doing this, but I'd like to restrict where my screenshot service can be called from. A whitelist of allowed IP addresses would make sense to me.  If there is another way to restrict callers, I'd like to know. Thanks!

**Comment by vbauer** [comment]
I think you can configure Firewall to prevent some unnecessary clients, but maybe it will be useful to add this feature inside Manet.

**Comment by vbauer** [comment]
I've just updated info about whitelist. Not it is based on [url-pattern](https://github.com/snd/url-pattern) library. This project contains a lot of examples of usage in README.
