### ISSUE TITLE
Crash on invalid engine value

### ISSUE THREAD

**Issue by ei-grad** [vbauer/manet#49]
```
/usr/local/lib/node_modules/manet/src/capture.js:38
 command = config.command || config.commands[engine][process.platform];
                                                             ^

TypeError: Cannot read property 'linux' of undefined
    at cliCommand (/usr/local/lib/node_modules/manet/src/capture.js:38:62)
    at runCapturingProcess (/usr/local/lib/node_modules/manet/src/capture.js:91:21)
    at retrieveImageFromSite (/usr/local/lib/node_modules/manet/src/capture.js:125:15)
    at /usr/local/lib/node_modules/manet/src/capture.js:137:51
    at FSReqWrap.cb [as oncomplete] (fs.js:216:19)
```

**Comment by vbauer** [comment]
Thank you for information. Fixed.
